project_name: outline-vpn
before:
  hooks:
    - go mod tidy
builds:
  - binary: outline-vpn
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - -s -w
      - -X main.outline-vpnVersion={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64      
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: ghdwlsgur
    name: outline-vpn
brews:
  - name: outline-vpn
    homepage: "https://github.com/ghdwlsgur/outline-vpn"
    description: "outline-vpn helps you easily and quickly provision EC2 with terraform and consume vpn service on your mobile or computer via outline application."
    repository:
      owner: ghdwlsgur
      name: homebrew-outline-vpn
    commit_author:
      name: ghdwlsgur
      email: vjinhyeokv@gmail.com
